[book]
title = "Six Principles (Transcribed)"
authors = ["William Perkins"]
language = "en"
multilingual = false
src = "./"
summary = "\"To bring you to true knowledge, vnfained faith, and ſound repentance: here I haue ſet downe the principall points of Chriſtian religion in ſixe plaine and eaſie rules: euen ſuch as the ſimpleſt may eaſily learne: and hereunto is adioyned and expoſition of them word by word.\" - William Perkins"

[build]
build-dir = "../../../dist/t/six-principles"

[output.html]
default-theme = "rust"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/glitchassassin/william-perkins"
edit-url-template = "https://github.com/glitchassassin/william-perkins/edit/master/{path}"
site-url = "/t/six-principles"
additional-css = ["themes/themes.css"]
