[book]
title = "An Exposition of the Lord's Prayer (Transcribed)"
authors = ["William Perkins"]
language = "en"
multilingual = false
src = "./"
summary = "An expoſition of the Lord's Prayer, in the way of catechizing, ſerving for ignorant people. Hereunto are adioyned the prayers of PAVL, taken out of his Epiſtles."

[build]
build-dir = "../../../dist/t/lords-prayer"

[output.html]
default-theme = "rust"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/glitchassassin/william-perkins"
edit-url-template = "https://github.com/glitchassassin/william-perkins/edit/master/{path}"
site-url = "/t/lords-prayer"
additional-css = ["themes/themes.css"]
no-section-label = true
