[book]
title = "An Exposition of the Apostles' Creed (Transcribed)"
authors = ["William Perkins"]
language = "en"
multilingual = false
src = "./"
summary = "AN EXPOSITION OF THE SYMBOLE, OR CREED OF THE APOSTLES: According to the tenour of the Scripture, and the conſent of Orthodoxe Fathers of the CHVRCH."

[build]
build-dir = "../../../dist/t/apostles-creed"

[output.html]
default-theme = "rust"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/glitchassassin/william-perkins"
edit-url-template = "https://github.com/glitchassassin/william-perkins/edit/master/{path}"
site-url = "/t/apostles-creed"
additional-css = ["themes/themes.css"]
no-section-label = true
