# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: ./stats/package-lock.json
    - run: npm ci
      working-directory: ./stats
    - run: npm run build
      working-directory: ./stats
    - name: Publish stats
      uses: actions/upload-artifact@v3
      with:
        name: stats
        path: stats/dist
  books:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache mdbook
      uses: actions/cache@v3
      env:
        cache-name: cache-cargo
      with:
        # cargo cache files are stored in `~/.cargo` on Linux/macOS
        path: ~/.cargo
        key: ${{ env.cache-name }}-mdbook-0.4.18
    - name: Dependencies
      run: cargo install mdbook --version 0.4.18
    - name: Build books
      run: ./build.sh
      working-directory: ./books/
    - name: Publish books
      uses: actions/upload-artifact@v3
      with:
        name: books
        path: dist
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [books, stats]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
    - name: Collate
      run: |
        cp -r -T books/ ./dist
        cp -r -T stats/ ./dist
        touch ./dist/.nojekyll
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.
