on:
  issues:
    types: [closed]

name: Create issue for Revision step
jobs:
  stuff:
    if: contains(github.event.issue.labels.*.name, 'transcription')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: filterChapter
        run: |
          echo "::debug::$(echo \"${{ github.event.issue.title }}\" | sed \"s/\\[.*\\] //g\")"
          echo "::set-output name=PREV_CHAPTER::$(echo \"${{ github.event.issue.title }}\" | sed \"s/\\[.*\\] //g\")"
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREV_CHAPTER: ${{ steps.filterChapter.outputs.PREV_CHAPTER }}
          TRANSCRIPTION: ${{ github.event.issue.html_url }}
        with:
          filename: .github/AUTO_ISSUE_TEMPLATE/revise-chapter.md
