on:
  issues:
    types: [closed]

name: Create issue for Revision step
jobs:
  stuff:
    if: contains(github.event.issue.labels.*.name, 'transcription')
    runs-on: ubuntu-latest
    steps:
      - id: filterChapter
        run: echo "::set-output name=PREV_CHAPTER::${{ github.event.issue.title }}" | sed "s/\[.+\]//g"
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREV_CHAPTER: ${{ steps.filterChapter.outputs.PREV_CHAPTER}}
        with:
          filename: .github/AUTO_ISSUE_TEMPLATE/revise-chapter.md